/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        PessoaALT_TXT.setVisible(false);
        PessoaPESO_TXT.setVisible(false);
        PessoaIDADE_TXT.setVisible(false);
        PessoaIMC_TXT.setVisible(false);
        PessoaNOME_TXT.setVisible(false);
        PessoaCLASS_TXT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        NOME_TXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PESO_TXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ALTURA_TXT = new javax.swing.JTextField();
        IDADE_TXT = new javax.swing.JTextField();
        SAIR_BTN = new javax.swing.JButton();
        CALCULAR_BTN = new javax.swing.JButton();
        LIMPAR_BTN = new javax.swing.JButton();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        scrollBarCustom1 = new org.edisoncor.gui.scrollBar.ScrollBarCustom();
        PessoaNOME_TXT = new javax.swing.JLabel();
        PessoaPESO_TXT = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PessoaALT_TXT = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PessoaIDADE_TXT = new javax.swing.JLabel();
        PessoaIMC_TXT = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PessoaCLASS_TXT = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Calcular IMC");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 0, 170, 70);

        panelImage1.setEnabled(false);
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Classificação+do+IMC+para+adultos.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1);
        panelImage1.setBounds(30, 60, 350, 190);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Idade:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 330, 60, 30);

        NOME_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOME_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(NOME_TXT);
        NOME_TXT.setBounds(180, 290, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Altura:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 410, 60, 30);

        PESO_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESO_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(PESO_TXT);
        PESO_TXT.setBounds(180, 370, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Peso:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 370, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nome: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 290, 60, 30);

        ALTURA_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTURA_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(ALTURA_TXT);
        ALTURA_TXT.setBounds(180, 410, 100, 30);

        IDADE_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDADE_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(IDADE_TXT);
        IDADE_TXT.setBounds(180, 330, 100, 30);

        SAIR_BTN.setText("X");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN);
        SAIR_BTN.setBounds(620, 10, 50, 50);

        CALCULAR_BTN.setText("Calcular");
        CALCULAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(CALCULAR_BTN);
        CALCULAR_BTN.setBounds(130, 490, 90, 40);

        LIMPAR_BTN.setText("Limpar");
        LIMPAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(LIMPAR_BTN);
        LIMPAR_BTN.setBounds(240, 490, 90, 40);

        panelImage2.setEnabled(false);
        panelImage2.setFocusable(false);
        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/stantingman.png"))); // NOI18N
        panelImage2.setOpaque(false);
        panelImage2.setRequestFocusEnabled(false);
        panelImage2.setLayout(null);

        scrollBarCustom1.setVisibleAmount(0);
        scrollBarCustom1.setEnabled(false);
        panelImage2.add(scrollBarCustom1);
        scrollBarCustom1.setBounds(150, 100, 17, 350);

        PessoaNOME_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PessoaNOME_TXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelImage2.add(PessoaNOME_TXT);
        PessoaNOME_TXT.setBounds(190, 50, 90, 40);

        PessoaPESO_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PessoaPESO_TXT.setForeground(new java.awt.Color(255, 255, 255));
        PessoaPESO_TXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelImage2.add(PessoaPESO_TXT);
        PessoaPESO_TXT.setBounds(210, 200, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Peso:");
        panelImage2.add(jLabel8);
        jLabel8.setBounds(210, 170, 60, 30);

        PessoaALT_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelImage2.add(PessoaALT_TXT);
        PessoaALT_TXT.setBounds(80, 280, 70, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Altura:");
        panelImage2.add(jLabel10);
        jLabel10.setBounds(80, 250, 60, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Idade:");
        panelImage2.add(jLabel11);
        jLabel11.setBounds(270, 90, 60, 30);

        PessoaIDADE_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelImage2.add(PessoaIDADE_TXT);
        PessoaIDADE_TXT.setBounds(330, 90, 70, 30);

        PessoaIMC_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelImage2.add(PessoaIMC_TXT);
        PessoaIMC_TXT.setBounds(330, 120, 70, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("IMC:");
        panelImage2.add(jLabel14);
        jLabel14.setBounds(270, 120, 60, 30);

        PessoaCLASS_TXT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panelImage2.add(PessoaCLASS_TXT);
        PessoaCLASS_TXT.setBounds(280, 300, 110, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Classificação:");
        panelImage2.add(jLabel16);
        jLabel16.setBounds(280, 270, 110, 40);

        jPanel1.add(panelImage2);
        panelImage2.setBounds(270, 80, 480, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(680, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NOME_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOME_TXTActionPerformed
       
    }//GEN-LAST:event_NOME_TXTActionPerformed

    private void IDADE_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDADE_TXTActionPerformed
        
    }//GEN-LAST:event_IDADE_TXTActionPerformed

    private void PESO_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESO_TXTActionPerformed
        
    }//GEN-LAST:event_PESO_TXTActionPerformed

    private void ALTURA_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTURA_TXTActionPerformed
        
    }//GEN-LAST:event_ALTURA_TXTActionPerformed

    private void CALCULAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_BTNActionPerformed
        Model.Funcoes_DAO.calcular();
        Model.Funcoes_DAO.showRes();
    }//GEN-LAST:event_CALCULAR_BTNActionPerformed

    private void LIMPAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPAR_BTNActionPerformed
        Model.Funcoes_DAO.limpar();
    }//GEN-LAST:event_LIMPAR_BTNActionPerformed

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        Model.Funcoes_DAO.sair();
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField ALTURA_TXT;
    private javax.swing.JButton CALCULAR_BTN;
    public static javax.swing.JTextField IDADE_TXT;
    private javax.swing.JButton LIMPAR_BTN;
    public static javax.swing.JTextField NOME_TXT;
    public static javax.swing.JTextField PESO_TXT;
    public static javax.swing.JLabel PessoaALT_TXT;
    public static javax.swing.JLabel PessoaCLASS_TXT;
    public static javax.swing.JLabel PessoaIDADE_TXT;
    public static javax.swing.JLabel PessoaIMC_TXT;
    public static javax.swing.JLabel PessoaNOME_TXT;
    public static javax.swing.JLabel PessoaPESO_TXT;
    private javax.swing.JButton SAIR_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.scrollBar.ScrollBarCustom scrollBarCustom1;
    // End of variables declaration//GEN-END:variables
}
